# Site settings
title: Rails Girls Auckland
email: railsgirlsauckland@gmail.com
description: "The blog for Rails Girls Auckland."
baseurl: "/railsgirlsblog"
url: ""

# Build settings
markdown: kramdown
permalink: pretty
